
[functions.sync-telegram-stats]
enabled = true
verify_jwt = false
import_map = "./functions/sync-telegram-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-telegram-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-telegram-stats/*.html" ]

[functions.telegram-webhook]
verify_jwt = false

[functions.verify-channel]
verify_jwt = false

